# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: de96347a5129177b9e45b3216826e524e4944260e68bbf2e05010e80f1a6d560783f63d23b14677bae83d130b497da19677fbf2431b2212b08e4007e4ee1f4c9

test:
  secret_key_base: c6b5af12a6d31ff2c5ecc352daba77a571e28c91ded170ccc75c77f29bc1ec022c0cab0e948df9f5a1f3695979342d28189f1c83297a47a03df9836ec31af050

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
